class PC:
    def __init__(self):
        self.MSG_TYPE = "msg_type"
        self.HEARTBEAT = "heart_beat"
        self.CLIENT_ID = "client_id"
        self.ERROR = "error"
        self.ERR_NOT_FOUND = "not_found"
        self.REGISTER = "register"
        self.UNREGISTER = "unregister"
        self.ACTION_REQUIRED = "action"
        self.PAUSE_REQUIRED = "pause_action"
        self.PAUSED = "paused"
        self.RESUMED_REQUIRED = "resume_action"
        self.RESUMED = "resumed"
        self.SHUTDOWN_REQUIRED = "shutdown_action"
        self.SHUTDOWN = "shutdown"
        self.SERVER_STATUS = "server_status"
        self.STATUS_CONNECTION_LOST = "connection_lost"
        self.STATUS_RUNNING = "running"
        self.STATUS_PAUSED = "paused_server"
        self.STATUS_SHUTDOWN = "shutdown_server"
